In [ ]:
MODEL

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [2]:
df=pd.read_csv("Gurgaon_housing.csv")

In [3]:
df.isnull().sum()

Location                  0
Property_Type             0
Area_sqft                50
Bedrooms                 50
Bathrooms                50
Balcony                  50
Parking                  50
Age_of_Property_Years    50
Floor                     0
Total_Floors              0
Furnishing               50
Near_Metro               50
Price_INR                 0
dtype: int64

In [4]:
x=df.iloc[:, :-1]
y=df.iloc[:,-1]

In [5]:
y

0      28903086
1      16685358
2      56809959
3      15783089
4      44540715
         ...
495    60116489
496     8725231
497    58008669
498    33608333
499    11352916
Name: Price_INR, Length: 500, dtype: int64

In [6]:
x

,Location,Property_Type,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Furnishing,Near_Metro
0,Sector 56,Apartment,NaN,NaN,NaN,NaN,NaN,NaN,28,7,NaN,NaN
1,Sector 67,Apartment,1225.0,3.0,1.0,3.0,0.0,3.0,29,9,Fully Furnished,1.0
2,Sector 45,Apartment,NaN,NaN,NaN,NaN,NaN,NaN,17,34,NaN,NaN
3,Sector 45,Villa,1099.0,1.0,1.0,1.0,2.0,14.0,0,23,Unfurnished,1.0
4,Golf Course Road,Builder Floor,2297.0,3.0,4.0,3.0,0.0,19.0,27,9,Semi-Furnished,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Sector 56,Builder Floor,NaN,NaN,NaN,NaN,NaN,NaN,2,31,NaN,NaN
496,DLF Phase 1,Builder Floor,664.0,1.0,1.0,1.0,1.0,24.0,16,3,Fully Furnished,0.0
497,Sector 57,Apartment,NaN,NaN,NaN,NaN,NaN,NaN,12,1,NaN,NaN
498,DLF Phase 3,Apartment,2131.0,3.0,1.0,2.0,2.0,9.0,7,3,Semi-Furnished,0.0
499,Sector 57,Apartment,811.0,3.0,2.0,1.0,2.0,5.0,28,1,Unfurnished,0.0

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
x_train

,Location,Property_Type,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Furnishing,Near_Metro
239,Sector 56,Apartment,3639.0,3.0,4.0,1.0,1.0,2.0,7,18,Semi-Furnished,0.0
59,DLF Phase 3,Villa,1988.0,5.0,3.0,3.0,0.0,15.0,7,5,Semi-Furnished,1.0
406,Sohna Road,Apartment,NaN,NaN,NaN,NaN,NaN,NaN,23,3,NaN,NaN
391,DLF Phase 3,Apartment,566.0,5.0,2.0,2.0,0.0,10.0,24,2,Fully Furnished,1.0
411,Golf Course Road,Apartment,2346.0,4.0,1.0,0.0,1.0,2.0,6,4,Semi-Furnished,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
323,Sector 56,Villa,911.0,1.0,3.0,1.0,1.0,13.0,20,12,Fully Furnished,0.0
192,Sohna Road,Builder Floor,2053.0,5.0,4.0,2.0,0.0,10.0,14,17,Unfurnished,0.0
117,Golf Course Road,Apartment,1769.0,1.0,2.0,2.0,0.0,0.0,21,13,Fully Furnished,1.0
47,Sector 57,Apartment,2008.0,4.0,4.0,3.0,2.0,18.0,21,33,Fully Furnished,0.0
172,DLF Phase 2,Apartment,1452.0,5.0,1.0,3.0,1.0,0.0,11,26,Semi-Furnished,1.0

In [8]:
import numpy as np
housing_num=x_train.drop(["Location","Property_Type","Furnishing"],axis=1)
housing_num_test=x_test.drop(["Location","Property_Type","Furnishing"],axis=1)
housing_num
from sklearn.impute import SimpleImputer
SI=SimpleImputer(strategy="median")
housing_num = housing_num.select_dtypes(include=[np.number])
num_final=SI.fit_transform(housing_num)
num_final_test=SI.transform(housing_num_test)

In [9]:
num_final

array([[3.6390e+03, 3.0000e+00, 4.0000e+00, ..., 7.0000e+00, 1.8000e+01,
        0.0000e+00],
       [1.9880e+03, 5.0000e+00, 3.0000e+00, ..., 7.0000e+00, 5.0000e+00,
        1.0000e+00],
       [2.4745e+03, 3.0000e+00, 3.0000e+00, ..., 2.3000e+01, 3.0000e+00,
        0.0000e+00],
       ...,
       [1.7690e+03, 1.0000e+00, 2.0000e+00, ..., 2.1000e+01, 1.3000e+01,
        1.0000e+00],
       [2.0080e+03, 4.0000e+00, 4.0000e+00, ..., 2.1000e+01, 3.3000e+01,
        0.0000e+00],
       [1.4520e+03, 5.0000e+00, 1.0000e+00, ..., 1.1000e+01, 2.6000e+01,
        1.0000e+00]], shape=(375, 9))

In [10]:
housing_num_imputed=pd.DataFrame(num_final,columns=housing_num.columns,index=housing_num.index)
housing_num_imputed
housing_num_imputed_test=pd.DataFrame(num_final_test,columns=housing_num_test.columns,index=housing_num_test.index)
housing_num_imputed_test

,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Near_Metro
90,1661.0,1.0,2.0,0.0,0.0,4.0,12.0,17.0,0.0
254,3765.0,2.0,2.0,1.0,1.0,16.0,18.0,27.0,1.0
283,1086.0,5.0,1.0,3.0,2.0,1.0,9.0,9.0,0.0
445,2986.0,5.0,2.0,1.0,0.0,17.0,3.0,23.0,0.0
461,2252.0,3.0,2.0,1.0,1.0,10.0,13.0,32.0,0.0
...,...,...,...,...,...,...,...,...,...
430,2095.0,4.0,2.0,2.0,1.0,12.0,20.0,11.0,0.0
49,1010.0,1.0,2.0,2.0,1.0,3.0,25.0,21.0,0.0
134,769.0,3.0,1.0,0.0,1.0,9.0,29.0,31.0,0.0
365,4360.0,5.0,3.0,1.0,2.0,14.0,23.0,32.0,1.0
413,1356.0,3.0,1.0,0.0,2.0,17.0,24.0,6.0,0.0

In [11]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
housing_num_imputed_scaled=SC.fit_transform(housing_num_imputed)
housing_num_imputed_scaled_test=SC.transform(housing_num_imputed_test)

In [12]:
housing_num_imputed_scaled=pd.DataFrame(housing_num_imputed_scaled,columns=housing_num_imputed.columns,index=housing_num_imputed.index)
housing_num_imputed_scaled_test=pd.DataFrame(housing_num_imputed_scaled_test,columns=housing_num_imputed_test.columns,index=housing_num_imputed_test.index)

In [13]:
housing_num_imputed_scaled
housing_num_imputed_scaled_test

,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Near_Metro
90,-0.773986,-1.512469,-0.532998,-1.561615,-1.289343,-1.144164,-0.217383,-0.054074,-0.677602
254,1.167534,-0.759247,-0.532998,-0.598448,-0.006840,0.607703,0.470539,0.939940,1.475793
283,-1.304582,1.500418,-1.466991,1.327887,1.275663,-1.582131,-0.561344,-0.849285,-0.677602
445,0.448692,1.500418,-0.532998,-0.598448,-1.289343,0.753692,-1.249267,0.542334,-0.677602
461,-0.228626,-0.006026,-0.532998,-0.598448,-0.006840,-0.268230,-0.102730,1.436946,-0.677602
...,...,...,...,...,...,...,...,...,...
430,-0.373502,0.747196,-0.532998,0.364719,-0.006840,0.023748,0.699846,-0.650483,-0.677602
49,-1.374713,-1.512469,-0.532998,0.364719,-0.006840,-1.290153,1.273114,0.343531,-0.677602
134,-1.597102,-0.006026,-1.466991,-1.561615,-0.006840,-0.414219,1.731729,1.337545,-0.677602
365,1.716586,1.500418,0.400994,-0.598448,1.275663,0.315725,1.043807,1.436946,1.475793
413,-1.055433,-0.006026,-1.466991,-1.561615,1.275663,0.753692,1.158461,-1.147490,-0.677602

In [14]:
#lets deal with CAtegorical Values
housing_cat=x_train[["Location","Property_Type","Furnishing"]]
housing_cat
housing_cat_test=x_test[["Location","Property_Type","Furnishing"]]

In [15]:
from sklearn.preprocessing import OneHotEncoder
OHE=OneHotEncoder()
encoded_house_cat=OHE.fit_transform(housing_cat)
encoded_house_cat_test=OHE.transform(housing_cat_test)

In [16]:
encoded_house_cat.toarray()

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]], shape=(375, 16))

In [17]:
encoded_house_cat1=pd.DataFrame(encoded_house_cat.toarray(),columns=OHE.get_feature_names_out(housing_cat.columns),index=housing_cat.index)
encoded_house_cat1_test=pd.DataFrame(encoded_house_cat_test.toarray(),columns=OHE.get_feature_names_out(housing_cat_test.columns),index=housing_cat_test.index)

In [18]:
encoded_house_cat1

,Location_DLF Phase 1,Location_DLF Phase 2,Location_DLF Phase 3,Location_Golf Course Road,Location_Sector 45,Location_Sector 56,Location_Sector 57,Location_Sector 67,Location_Sohna Road,Property_Type_Apartment,Property_Type_Builder Floor,Property_Type_Villa,Furnishing_Fully Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Furnishing_nan
239,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
59,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
406,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
391,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
411,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
117,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
47,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
172,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [19]:
encoded_house_cat1_test

,Location_DLF Phase 1,Location_DLF Phase 2,Location_DLF Phase 3,Location_Golf Course Road,Location_Sector 45,Location_Sector 56,Location_Sector 57,Location_Sector 67,Location_Sohna Road,Property_Type_Apartment,Property_Type_Builder Floor,Property_Type_Villa,Furnishing_Fully Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Furnishing_nan
90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
254,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
283,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
445,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
461,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
49,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
134,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
413,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [20]:
x_train_final=np.hstack([housing_num_imputed_scaled,encoded_house_cat1])
x_train_final
x_test_final=np.hstack([housing_num_imputed_scaled_test,encoded_house_cat1_test])
x_test_final

array([[-0.7739863 , -1.51246905, -0.53299835, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.16753423, -0.75924741, -0.53299835, ...,  1.        ,
         0.        ,  0.        ],
       [-1.30458245,  1.50041751, -1.46699079, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.59710241, -0.00602577, -1.46699079, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.7165859 ,  1.50041751,  0.40099409, ...,  0.        ,
         1.        ,  0.        ],
       [-1.05543295, -0.00602577, -1.46699079, ...,  0.        ,
         1.        ,  0.        ]], shape=(125, 25))

In [21]:
                                                #OR

In [22]:
num_features = housing_num.columns
cat_features = OHE.get_feature_names_out(housing_cat.columns)

all_features = np.concatenate([num_features, cat_features])

x_train_final_df = pd.DataFrame(
    x_train_final,
    columns=all_features,
    index=x_train.index
)
#test set
num_features = housing_num.columns
cat_features = OHE.get_feature_names_out(housing_cat.columns)

all_features = np.concatenate([num_features, cat_features])

x_test_final_df = pd.DataFrame(
    x_test_final,
    columns=all_features,
    index=x_test.index
)

In [23]:
x_train_final_df

,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Near_Metro,Location_DLF Phase 1,...,Location_Sector 57,Location_Sector 67,Location_Sohna Road,Property_Type_Apartment,Property_Type_Builder Floor,Property_Type_Villa,Furnishing_Fully Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Furnishing_nan
239,1.051264,-0.006026,1.334987,-0.598448,-0.006840,-1.436142,-0.790652,0.045327,-0.677602,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
59,-0.472239,1.500418,0.400994,1.327887,-1.289343,0.461714,-0.790652,-1.246891,1.475793,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
406,-0.023308,-0.006026,0.400994,0.364719,-0.006840,0.023748,1.043807,-1.445694,-0.677602,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
391,-1.784426,1.500418,-0.532998,0.364719,-1.289343,-0.268230,1.158461,-1.545095,1.475793,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
411,-0.141885,0.747196,-1.466991,-1.561615,-0.006840,-1.436142,-0.905305,-1.346292,-0.677602,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,-1.466068,-1.512469,0.400994,-0.598448,-0.006840,0.169737,0.699846,-0.551081,-0.677602,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
192,-0.412258,1.500418,1.334987,0.364719,-1.289343,-0.268230,0.011924,-0.054074,-0.677602,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
117,-0.674326,-1.512469,-0.532998,0.364719,-1.289343,-1.728120,0.814500,-0.451680,1.475793,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
47,-0.453783,0.747196,1.334987,1.327887,1.275663,0.899681,0.814500,1.536348,-0.677602,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
172,-0.966846,1.500418,-1.466991,1.327887,-0.006840,-1.728120,-0.332037,0.840538,1.475793,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [24]:
x_test_final_df

,Area_sqft,Bedrooms,Bathrooms,Balcony,Parking,Age_of_Property_Years,Floor,Total_Floors,Near_Metro,Location_DLF Phase 1,...,Location_Sector 57,Location_Sector 67,Location_Sohna Road,Property_Type_Apartment,Property_Type_Builder Floor,Property_Type_Villa,Furnishing_Fully Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Furnishing_nan
90,-0.773986,-1.512469,-0.532998,-1.561615,-1.289343,-1.144164,-0.217383,-0.054074,-0.677602,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
254,1.167534,-0.759247,-0.532998,-0.598448,-0.006840,0.607703,0.470539,0.939940,1.475793,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
283,-1.304582,1.500418,-1.466991,1.327887,1.275663,-1.582131,-0.561344,-0.849285,-0.677602,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
445,0.448692,1.500418,-0.532998,-0.598448,-1.289343,0.753692,-1.249267,0.542334,-0.677602,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
461,-0.228626,-0.006026,-0.532998,-0.598448,-0.006840,-0.268230,-0.102730,1.436946,-0.677602,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,-0.373502,0.747196,-0.532998,0.364719,-0.006840,0.023748,0.699846,-0.650483,-0.677602,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
49,-1.374713,-1.512469,-0.532998,0.364719,-0.006840,-1.290153,1.273114,0.343531,-0.677602,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
134,-1.597102,-0.006026,-1.466991,-1.561615,-0.006840,-0.414219,1.731729,1.337545,-0.677602,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
365,1.716586,1.500418,0.400994,-0.598448,1.275663,0.315725,1.043807,1.436946,1.475793,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
413,-1.055433,-0.006026,-1.466991,-1.561615,1.275663,0.753692,1.158461,-1.147490,-0.677602,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [25]:
DTR=DecisionTreeRegressor(random_state=0)
DTR.fit(x_train_final_df,y_train)

DecisionTreeRegressor(random_state=0)

In [26]:
y_pred=DTR.predict(x_test_final_df)
print(y_pred)

[26708257. 60557246. 19468787. 30260519. 30554121. 71604321. 27109574.
 55954959. 44540715. 20223375. 25268088. 37608113. 25682963. 48733674.
  6465047. 80415397. 39742595. 31752220. 30665977. 14999233. 62204077.
 23854790. 76267333. 51009245. 29222542. 41878717. 19031990. 16293204.
  9252158. 19273095.  8956187. 55954959. 26197851. 22550202. 26197851.
 39957473. 45669367. 42891406. 62204077. 30665977. 15783089. 26708257.
 62715169. 25215888. 30554121. 19468787. 61200355. 62204077. 19468787.
 25682963. 37616956. 20369333. 79593175. 57680522. 14127894.  6964997.
 29222542. 30554121. 67184793. 54449016. 30554121. 19798719.  9252158.
 14452775.  7893218. 33854072. 11352916. 33608333. 45528862. 38576180.
 36221728. 62204077. 14127894. 30899089. 72566031. 29020073. 19398752.
 54773945. 30554121. 55954959.  9252158. 14127894. 36221728.  8551997.
 64739437. 50571410. 15324915. 19442576. 19398752. 33925097. 28945526.
 41549073. 52328393. 19031990. 13927142. 59530457. 20417263. 36221728.
 28880324. 60557246. 47800354. 30554121. 59530457. 45669367. 67016220.
 47892429. 52788695. 33925097. 54150163. 38576180. 26596091.  8754223.
  9192209.  8754223. 52992524. 34876638. 80415397. 21488803. 82058041.
 21748813. 25682963. 14369823. 14127894. 37558600. 26708257.]

In [27]:
print(y_test)

90     30351392
254    60191629
283    21573045
445    26673135
461    20867852
         ...
430    26436179
49     15892355
134    14058185
365    40513457
413    24110824
Name: Price_INR, Length: 125, dtype: int64

In [29]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse=np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

RMSE: 7760792.037442281
R2 Score: 0.8361428437296192